#!/usr/bin/env python

#===============================================================================
# Hor+ FOV calculator - hor+fovcalc
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# WTF is this?
#   A script for calculating the Vert- horizontal fov for your aspect ratio that
#   will keep the same vertical fov as someone who play on specified horizontal
#   FOV on a monitor with 4:3 aspect ratio
#
# Who made this?
#   My little commie <3
#===============================================================================

import sys
import math

def usage():
    sys.stderr.write("""\
Hor+ FOV calculator
===================

Usage:
  %s <hfov at 4:3> <aspect>

Options:
  <hfov at 4:3> - The horizontal fov at 4:3 aspect ratio
  <aspect> - The aspect ratio of the current monitor

Example:
   How to get the correct cg_fov in OpenArena if I want 90 Hor+ fov?
     %s 90 16:9
""" % (sys.argv[0], sys.argv[0]))
    sys.exit(1)

def error(msg):
    sys.stderr.write(msg)
    sys.exit(1)

def tand(x):
    return math.tan(math.radians(x))

def atand(x):
    return math.degrees(math.atan(x))

def vfov_to_hfov(vfov, aspect):
    return 2.0 * atand(tand(vfov / 2.0) * aspect)

def hfov_to_vfov(hfov, aspect):
    return 2.0 * atand(tand(hfov / 2.0) / aspect)

def parse_aspect(s):
    a = s.split(":")
    if len(a) != 2:
        raise ValueError("Could not convert string to aspect ratio %s", s)
    return float(a[0]) / float(a[1])

def main():
    if len(sys.argv) < 3:
        usage()

    try:    
        hfov_at_4_3 = float(sys.argv[1])
    except:
        error("Invalid number argument: %s" % sys.argv[1]);

    try:
        aspect = parse_aspect(sys.argv[2])
    except:
        error("Invalid aspect-ratio argument: %s" % sys.argv[2]);

    vfov = hfov_to_vfov(hfov_at_4_3, 4.0 / 3.0)
    hfov = vfov_to_hfov(vfov, aspect)
    print(hfov)

if __name__ == "__main__":
    main()
