#!/usr/bin/env python

#===============================================================================
# Hor+ FOV calculator - hor+fovcalc
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# WTF is this?
#   A script for calculating the Vert- horizontal fov for your aspect ratio that
#   will keep the same vertical fov as someone who play on specified horizontal
#   FOV on a monitor with 4:3 aspect ratio
#
# Who made this?
#   My little commie <3
#===============================================================================

import argparse
import sys
import math

"""
Hor+ FOV calculator.

A script for calculating the Vert- horizontal fov for your aspect ratio that
will keep the same vertical fov as someone who play on specified horizontal
FOV on a monitor with 4:3 aspect ratio.
"""

def error(msg):
    sys.stderr.write(msg)
    sys.exit(1)

def tand(x):
    return math.tan(math.radians(x))

def atand(x):
    return math.degrees(math.atan(x))

def vfov_to_hfov(vfov, aspect):
    return 2.0 * atand(tand(vfov / 2.0) * aspect)

def hfov_to_vfov(hfov, aspect):
    return 2.0 * atand(tand(hfov / 2.0) / aspect)

def parse_aspect(s):
    a = s.split(":")
    if len(a) != 2:
        raise ValueError("Could not convert string to aspect ratio %s", s)
    return float(a[0]) / float(a[1])

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        '--hor-fov',
        help='The horizontal fov at 4:3 aspect ratio',
        type=float,
        required=True,
    )
    parser.add_argument(
        '--aspect',
        help='The aspect ratio of the current monitor',
        type=str,
        required=True,
    )
    args = parser.parse_args()

    try:
        aspect = parse_aspect(args.aspect)
    except:
        error("Invalid aspect-ratio argument: %s" % args.aspect);

    vfov = hfov_to_vfov(args.hor_fov, 4.0 / 3.0)
    hfov = vfov_to_hfov(vfov, aspect)
    print(hfov)

if __name__ == "__main__":
    main()
